[Setting1]
FieldWidth = 5000.0 ;
FieldHight = 5000.0 ;
field_name = itukaichi;フィールドの名前jsonデータの名前と同じものを設定
Num_user = 10 ;ユーザ数
Add_user = 1 ;追加ユーザ数

;2026-04-14
Num_user = 600
Add_user = 500
AddUsersPerInterval = 5
AddUserStartTime = 0.0
AddUserEndTime = 100000000.0
AddUserInterval = 10.0
MeasureStartTime = 0.0
MeasureEndTime = 100000000.0

;UserDataSize=100

Auto_ferry_num = true ;避難所の数だけドローンを飛行させるかどうか
Num_ferry = 1 ;フェリーノードの数
Ferry_start_node = node/11732;
Ferry_HelloInterval = 5.0;フェリーノードのHello送信間隔
UserSpeed = 1.6 ;ユーザスピード
FerryNodeSpeed = 10.0;フェリーノードのスピード(m/s)
HelloInterval = 20.0 ;Helloパケット送出間隔
ShelterDataInterval = 60.0 ; 避難所からのデータ送信間隔
UpdateMapinfoInterval = 50.0 ;地図を更新する間隔の設定
blockflag = true ;通行止め箇所を設定するかどうか
blockeraseflag = false ;通行止め箇所を途中で削除するかどうか
randomblockeraseflag = false ;ランダムで一つづつ通行止め箇所を削除するかどうか
setexitAutoflag = true ;自動で避難所を設定するかどうか
setexitmanualflag = false ;手動で設定した避難所を読み込むかどうか
setnearly = 300 ;避難所を自動で読み込む場合の入り口として設定するノードの近さ

RandomUserSpeedFlag = false ;ユーザースピードをそれぞれのノードでランダムにするかどうか
MinSpeed = 1.0 ;ユーザスピードの最小値
MaxSpeed = 2.0 ;ユーザスピードの最大値

useexitinfo = true ;避難所の収容人数を考慮した選択を行うかどうか(現在コマンドから指定)
UseDisasterType = false ;災害の種類に応じて避難所を選択するかどうか
Disaster_Type = 2 ;地震：1, 津波：2, 水害：3, 火山：4, その他：5

AoI = 60 ;QuickSendをするときのAoIのしきい値(指定した値以下だと早くする)
UseQuickSend = true ;AoI値によりHelloの間隔を短くするかどうか(今は使ってない現在はコマンドから指定)
QuickHelloInterval = 20.0 ;QuickSendを使うときのHello間隔

;AddUserInterval = 1.0 ;ユーザを追加する間隔
moving_user_check_interval = 1.0 ;ユーザ数をチェックする間隔
eraseAoI = 500 ;情報を捨てるAoI値(使っていないコマンドから指定)
quick_hello_times = 3 ;QuickHelloをする回数

Set_rescue_flag = false ;要救助者を設定（画像ファイルが生成されるノードを設定する）
Erase_rescue_flag = false ;要救助者を削除（画像ファイルが生成されるノードを削除）
Set_congestion_flag = true ;混雑箇所を設定
Erase_congestion_flag = true ;混雑箇所を削除

SendHopFlag = false ;Hopを使った収容人数予測をするかどうか(今は使ってない現在はコマンドから指定)

[json_data]
SimulationFieldMap = ./obayashiIOFiles/data/field_json/koi.geojson ;シミュレーションフィールドのファイルパス（使ってない！！変更したい場合はfield_nameを変更すること！)
hinanjo_json = ./obayashiIOFiles/data/hinanjo.geojson ;避難所のJsonファイル



